import { useState } from "react";
import { ArrowRight, CheckCircle2, Factory, Package, Play, Save } from "lucide-react";
import { useDemo } from "../state/DemoContext";
import { PageHeader } from "../components/ui/PageHeader";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Modal } from "../components/ui/Modal";

export function BulkPackagingPage({onNavigate}){
  const {state,dispatch}=useDemo();
  const [creating,setCreating]=useState(false);
  const [finishing,setFinishing]=useState(null);
  const orders=[...(state.packagingOrders||[])].sort((a,b)=>numberOf(b.id)-numberOf(a.id));
  const current=orders.find(order=>order.status!=="Terminada")||orders[0];
  const completed=orders.filter(order=>order.status==="Terminada");

  function createOrder(values){
    const recipe=state.recipes.find(item=>item.id===values.recipeId);
    const sourceLot=state.lots.find(item=>item.id===values.sourceLotId);
    const sourceComponent=recipe.components.find(item=>item.product===sourceLot.product);
    const scale=Number(values.plannedQty)/Number(recipe.outputQty);
    const components=recipe.components.map(component=>{const lot=component.product===sourceLot.product?sourceLot:state.lots.find(item=>item.product===component.product&&Number(item.qty)>0&&!["Bloqueado","Cuarentena"].includes(item.status));return {...component,qty:round(Number(component.qty)*scale),lotId:lot?.id||""}});
    const sequence=Math.max(0,...orders.map(order=>numberOf(order.id)))+1;
    const productionOrder=state.productionOrders.find(order=>order.outputLotId===sourceLot.id);
    dispatch({type:"ADD",collection:"packagingOrders",value:{...values,id:`ENV-2026-${String(sequence).padStart(3,"0")}`,productionOrderId:productionOrder?.id||sourceLot.origin,product:recipe.name,unit:recipe.outputUnit,plannedQty:Number(values.plannedQty),components,sourceConsumption:round(Number(sourceComponent?.qty||0)*scale),status:"Lista"}});
    setCreating(false);
  }
  function complete(values){dispatch({type:"COMPLETE_PACKAGING",value:{...values,producedQty:Number(values.producedQty),rejectedQty:Number(values.rejectedQty),status:"Terminada"}});setFinishing(null)}

  return <><PageHeader title="Órdenes de envasado" description="Convierte un lote base producido en presentaciones listas para inventario y venta." action="Nueva orden de envasado" onAction={()=>setCreating(true)}/>
    <section className="mb-4 grid gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="text-xs font-bold text-blue-900">Conexión con Producción</h2><p className="mt-1 text-[10px] leading-4 text-blue-800">Solo aparecen lotes base creados por una orden de producción terminada. Al finalizar el envasado, el nuevo lote queda disponible en Inventario, Ventas y Trazabilidad.</p></div><Button variant="secondary" onClick={()=>onNavigate("manufacturing")}><Factory className="size-4"/>Ver producción</Button></section>
    {current&&<PackagingCard order={current} lots={state.lots} onStart={()=>dispatch({type:"ADVANCE_PACKAGING",id:current.id,status:"En proceso"})} onFinish={()=>setFinishing(current)} onInventory={()=>onNavigate("inventory")} onTrace={()=>onNavigate("traceability")}/>}
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><header className="border-b border-slate-200 p-4"><h2 className="text-sm font-bold">Historial de envasado</h2><p className="text-[10px] text-slate-500">{completed.length} órdenes terminadas</p></header><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr>{["Orden","Origen de producción","Lote base","Producto obtenido","Cantidad","Lote final"].map(column=><th className="px-4 py-3" key={column}>{column}</th>)}</tr></thead><tbody>{completed.map(order=><tr className="border-t border-slate-100" key={order.id}><td className="px-4 py-3 font-semibold">{order.id}</td><td className="px-4 py-3">{order.productionOrderId}</td><td className="px-4 py-3">{order.sourceLotId}</td><td className="px-4 py-3">{order.product}</td><td className="px-4 py-3">{order.producedQty} {order.unit}</td><td className="px-4 py-3">{order.outputLotId}</td></tr>)}</tbody></table></div></section>
    {creating&&<CreatePackagingModal recipes={state.recipes} lots={state.lots} productionOrders={state.productionOrders} onClose={()=>setCreating(false)} onSave={createOrder}/>}
    {finishing&&<FinishPackagingModal order={finishing} onClose={()=>setFinishing(null)} onSave={complete}/>}
  </>;
}

function PackagingCard({order,lots,onStart,onFinish,onInventory,onTrace}){
  const ready=order.components.every(component=>component.lotId&&Number(lots.find(lot=>lot.id===component.lotId)?.qty||0)>=Number(component.qty));
  return <section className="rounded-xl border border-slate-200 bg-white"><header className="flex flex-col justify-between gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center"><div><small className="text-[9px] text-slate-400">{order.id} · desde {order.productionOrderId}</small><h2 className="text-lg font-bold">{order.product}</h2><p className="text-xs text-slate-500">Lote base: {order.sourceLotId} → {order.plannedQty} {order.unit}</p></div><Badge>{order.status}</Badge></header>
    <div className="p-5"><div className="mb-4 grid gap-3 sm:grid-cols-3"><Fact label="Orden de producción" value={order.productionOrderId}/><Fact label="Lote base" value={order.sourceLotId}/><Fact label="Resultado previsto" value={`${order.plannedQty} ${order.unit}`}/></div><div className="overflow-x-auto rounded-lg border border-slate-200"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr>{["Material","Lote asignado","Necesario","Disponible","Estado"].map(column=><th className="px-3 py-2" key={column}>{column}</th>)}</tr></thead><tbody>{order.components.map(component=>{const lot=lots.find(item=>item.id===component.lotId),enough=lot&&Number(lot.qty)>=Number(component.qty);return <tr className="border-t border-slate-100" key={component.product}><td className="px-3 py-3">{component.product}</td><td className="px-3 py-3">{component.lotId||"Sin lote"}</td><td className="px-3 py-3">{component.qty} {component.unit}</td><td className="px-3 py-3">{lot?`${lot.qty} ${lot.unit}`:"—"}</td><td className="px-3 py-3"><Badge>{enough?"Disponible":"Faltante"}</Badge></td></tr>})}</tbody></table></div>{!ready&&order.status!=="Terminada"&&<p className="mt-3 text-[10px] text-red-600">Faltan materiales o existencias para iniciar el envasado.</p>}</div>
    <footer className="flex flex-wrap justify-end gap-2 border-t border-slate-200 p-4">{order.status==="Terminada"?<><Button variant="secondary" onClick={onTrace}>Ver trazabilidad</Button><Button onClick={onInventory}>Ver lote en inventario <ArrowRight className="size-4"/></Button></>:order.status==="En proceso"?<Button onClick={onFinish}><CheckCircle2 className="size-4"/>Registrar resultado</Button>:<Button disabled={!ready} onClick={onStart}><Play className="size-4"/>Iniciar envasado</Button>}</footer>
  </section>;
}

function CreatePackagingModal({recipes,lots,productionOrders,onClose,onSave}){
  const sourceLots=lots.filter(lot=>productionOrders.some(order=>order.status==="Terminada"&&order.outputLotId===lot.id)&&["Producto en proceso","Producto intermedio"].includes(lot.type)&&Number(lot.qty)>0);
  const packagingRecipes=recipes.filter(recipe=>sourceLots.some(lot=>recipe.components.some(component=>component.product===lot.product)));
  const [form,setForm]=useState({sourceLotId:sourceLots[0]?.id||"",recipeId:packagingRecipes[0]?.id||"",plannedQty:packagingRecipes[0]?.outputQty||1});
  const recipe=recipes.find(item=>item.id===form.recipeId),source=lots.find(item=>item.id===form.sourceLotId),scale=recipe?Number(form.plannedQty)/Number(recipe.outputQty):0;
  return <Modal title="Nueva orden de envasado" onClose={onClose} size="lg"><form onSubmit={event=>{event.preventDefault();onSave(form)}} className="grid gap-5 p-5 sm:p-6">{sourceLots.length?<><section className="grid gap-4 sm:grid-cols-2"><Field label="Lote base producido *"><select value={form.sourceLotId} onChange={event=>setForm(current=>({...current,sourceLotId:event.target.value}))} className="input-agro">{sourceLots.map(lot=><option value={lot.id} key={lot.id}>{lot.product} · {lot.id} · {lot.qty} {lot.unit}</option>)}</select></Field><Field label="Receta de envasado *"><select value={form.recipeId} onChange={event=>{const next=recipes.find(item=>item.id===event.target.value);setForm(current=>({...current,recipeId:event.target.value,plannedQty:next.outputQty}))}} className="input-agro">{packagingRecipes.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label={`Cantidad a obtener (${recipe?.outputUnit||""}) *`}><input type="number" min="1" value={form.plannedQty} onChange={event=>setForm(current=>({...current,plannedQty:event.target.value}))} className="input-agro"/></Field><Fact label="Orden de producción origen" value={productionOrders.find(order=>order.outputLotId===source?.id)?.id||"No encontrada"}/></section><section className="rounded-xl border border-slate-200 p-4"><h3 className="text-xs font-bold">Materiales calculados</h3><div className="mt-3 grid gap-2">{recipe?.components.map(component=>{const required=round(Number(component.qty)*scale),lot=component.product===source?.product?source:lots.find(item=>item.product===component.product&&Number(item.qty)>0);return <div className="flex justify-between rounded-lg bg-slate-50 p-3 text-[10px]" key={component.product}><span>{component.product}</span><span><b>{required} {component.unit}</b> · {lot?lot.id:"Sin lote"}</span></div>})}</div></section><div className="flex justify-end gap-2 border-t border-slate-200 pt-4"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit"><Save className="size-4"/>Crear orden</Button></div></>:<div className="rounded-xl bg-amber-50 p-5 text-center"><h3 className="text-sm font-bold">No hay lotes base disponibles</h3><p className="mt-2 text-[10px] text-slate-600">Primero termina una orden de producción que genere un producto en proceso.</p><div className="mt-4"><Button variant="secondary" onClick={onClose}>Cerrar</Button></div></div>}</form></Modal>;
}

function FinishPackagingModal({order,onClose,onSave}){const [form,setForm]=useState({...order,producedQty:order.plannedQty,rejectedQty:0,outputLotId:`${initials(order.product)}-2026-${order.id.split("-").at(-1)}`,expiry:""});const update=(field,value)=>setForm(current=>({...current,[field]:value}));return <Modal title={`Resultado de envasado · ${order.id}`} onClose={onClose}><form onSubmit={event=>{event.preventDefault();onSave(form)}} className="grid gap-4 p-5"><p className="rounded-lg bg-blue-50 p-3 text-[10px] text-blue-800">Al confirmar se consumirán el lote base y los envases. El nuevo lote quedará disponible para venta.</p><div className="grid gap-4 sm:grid-cols-2"><Field label={`Cantidad conforme (${order.unit})`}><input required type="number" min="0" value={form.producedQty} onChange={event=>update("producedQty",event.target.value)} className="input-agro"/></Field><Field label="Cantidad rechazada"><input required type="number" min="0" value={form.rejectedQty} onChange={event=>update("rejectedQty",event.target.value)} className="input-agro"/></Field><Field label="Nuevo lote terminado"><input required value={form.outputLotId} onChange={event=>update("outputLotId",event.target.value)} className="input-agro"/></Field><Field label="Fecha de vencimiento"><input required type="date" value={toInputDate(form.expiry)} onChange={event=>update("expiry",toDisplayDate(event.target.value))} className="input-agro"/></Field></div><div className="flex justify-end gap-2 border-t border-slate-200 pt-4"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit"><Package className="size-4"/>Finalizar y crear lote</Button></div></form></Modal>}
function Field({label,children}){return <label className="grid gap-1.5 text-xs font-medium text-slate-700"><span>{label}</span>{children}</label>}
function Fact({label,value}){return <div className="rounded-lg bg-slate-50 p-3"><small className="text-[9px] text-slate-400">{label}</small><b className="mt-1 block text-xs">{value}</b></div>}
function numberOf(id=""){return Number(id.split("-").at(-1))||0}
function round(value){return Math.round(value*100)/100}
function initials(text){return text.split(" ").filter(word=>word.length>2).map(word=>word[0]).join("").slice(0,4).toUpperCase()}
function toInputDate(value=""){const [day,month,year]=value.split("/");return year?`${year}-${month}-${day}`:value}
function toDisplayDate(value=""){const [year,month,day]=value.split("-");return day?`${day}/${month}/${year}`:value}
