import { AlertTriangle, ArrowRight, Lock, RotateCcw } from "lucide-react";
import { useDemo } from "../state/DemoContext";
import { PageHeader } from "../components/ui/PageHeader";
import { Button } from "../components/ui/Button";
import { Badge } from "../components/ui/Badge";
import { GenealogyGraph } from "../features/traceability/GenealogyGraph";
import { Fact } from "./PurchasesPage";
export function IncidentsPage({route}){const {state,dispatch}=useDemo();if(route==="recalls")return <Recall state={state} dispatch={dispatch}/>;return <><PageHeader title="Incidentes" description="Localiza automáticamente los productos derivados y clientes afectados por un lote problemático."/><div className="grid gap-4 xl:grid-cols-[1fr_380px]"><section className="rounded-xl border border-red-200 bg-white"><header className="flex items-center gap-3 border-b border-red-100 p-5"><AlertTriangle className="size-7 text-red-600"/><div className="flex-1"><small className="text-[9px] font-bold text-red-600">LOTE PROBLEMÁTICO</small><h2 className="text-lg font-bold">ACE-2026-001 · Aceite vegetal</h2></div><Badge>{state.incident?"Bloqueado":"En investigación"}</Badge></header><div className="grid gap-3 p-5 sm:grid-cols-4"><Fact l="Orden afectada" v="OF-CHIPS-001"/><Fact l="Lote derivado" v="CHIP-2026-001"/><Fact l="Disponible" v="670 bolsas"/><Fact l="Entregado" v="300 bolsas"/></div><footer className="flex justify-end gap-2 border-t border-red-100 p-4"><Button variant={state.incident?"secondary":"danger"} onClick={()=>dispatch({type:"INCIDENT",value:!state.incident})}><Lock className="size-4"/>{state.incident?"Liberar lote":"Bloquear lotes afectados"}</Button></footer></section><aside className="rounded-xl border border-slate-200 bg-white p-4"><GenealogyGraph incident/></aside></div></>}
function Recall({state,dispatch}){const labels=["Lote afectado","Productos derivados","Clientes","Cantidades","Reporte"];return <><PageHeader title="Gestión de retiro" description="Asistente para controlar cantidades producidas, vendidas, recuperadas y pendientes."/><div className="mb-5 flex overflow-x-auto">{labels.map((l,i)=><button onClick={()=>dispatch({type:"RECALL_STEP",value:i+1})} className="flex min-w-40 items-center gap-2" key={l}><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${i+1<=state.recallStep?"bg-red-600 text-white":"bg-slate-200"}`}>{i+1}</span><b className="text-[10px]">{l}</b>{i<labels.length-1&&<ArrowRight className="ml-auto size-4 text-slate-300"/>}</button>)}</div><section className="rounded-xl border border-slate-200 bg-white p-6"><small className="font-bold text-red-600">PASO {state.recallStep} DE 5</small><h2 className="mt-2 text-xl font-bold">{labels[state.recallStep-1]}</h2><div className="mt-5 grid gap-3 sm:grid-cols-4"><Fact l="Producidas" v="970 bolsas"/><Fact l="Vendidas" v="300"/><Fact l="Disponibles" v="670"/><Fact l="Recuperadas" v="0"/></div><div className="mt-6 flex justify-end"><Button variant="danger" onClick={()=>dispatch({type:"RECALL_STEP",value:Math.min(5,state.recallStep+1)})}>{state.recallStep===5?"Generar reporte de retiro":"Continuar"}<ArrowRight className="size-4"/></Button></div></section></>}
